name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Change this if your default branch is different
  workflow_dispatch:  # Allows manual trigger from Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2  # Adjust to your Ruby version
          bundler-cache: true

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          gem install jekyll bundler
          bundle install

      # 4. Build the site
      - name: Build Jekyll site
        run: bundle exec jekyll build

      # 5. Deploy to gh-pages
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
          force_orphan: true
